export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const FETCH_SINGLE_CHARACTER = 'FETCH_SINGLE_CHARACTER';
export const REQUEST_SINGLE_CHARACTER = 'REQUEST_SINGLE_CHARACTER';
export const CLEAN_SINGLE_CHARACTER = 'CLEAN_SINGLE_CHARACTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
